### ISSUE TITLE
Possibly an issue?

### ISSUE THREAD

**Issue by InterGypsi** [ScalarVector1/StructureHelper#6]
#@ |
0
[12:34:47] [12/DEBUG] [tML]: Assembly Resolve: IceKracken_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> StructureHelper_0, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[12:34:47] [12/WARN] [tML]: Silently Caught Exception: 
System.MissingMethodException: Method not found: 'Void StructureHelper.StructureHelper.GenerateStructure(System.String, Terraria.DataStructures.Point16, Terraria.ModLoader.Mod, Boolean)'.
   at IceKracken.IceWorld.ArenaGen(GenerationProgress progress)
   at Terraria.World.Generation.WorldGenerator.GenerateWorld(GenerationProgress progress)
   at Terraria.WorldGen.generateWorld(Int32 seed, GenerationProgress customProgressObject)
   at DMD<Terraria.WorldGen::do_worldGenCallBack>(Object )
   at Terraria.WorldGen.worldGenCallBack(Object threadContext)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

[12:34:47] [12/ERROR] [tML]: A problem was encountered during world generation
Ice Kracken Arena Gen
System.MissingMethodException: Method not found: 'Void StructureHelper.StructureHelper.GenerateStructure(System.String, Terraria.DataStructures.Point16, Terraria.ModLoader.Mod, Boolean)'.
   at IceKracken.IceWorld.ArenaGen(GenerationProgress progress)
   at Terraria.World.Generation.WorldGenerator.GenerateWorld(GenerationProgress progress)
[12:34:47] [12/ERROR] [Terraria]: A problem was encountered during world generation
System.MissingMethodException: Method not found: 'Void StructureHelper.StructureHelper.GenerateStructure(System.String, Terraria.DataStructures.Point16, Terraria.ModLoader.Mod, Boolean)'.
   at Terraria.World.Generation.WorldGenerator.GenerateWorld(GenerationProgress progress)
   at Terraria.WorldGen.generateWorld(Int32 seed, GenerationProgress customProgressObject)
   at DMD<Terraria.WorldGen::do_worldGenCallBack>(Object )
   at Terraria.WorldGen.worldGenCallBack(Object threadContext)
[12:34:56] [1/DEBUG] [tML]: Process.Start (UseShellExecute = True): "https://forums.terraria.org/index.php?threads/.63670/" 
[12:38:08] [1/DEBUG] [tML]: Process.Start (UseShellExecute = True): "C:\Users\(user)\OneDrive\Documents\My Games\Terraria\ModLoader\Logs\client.log" 
[12:38:09] [1/DEBUG] [tML]: Process.Start (UseShellExecute = True): "C:\Users\(user)\OneDrive\Documents\My Games\Terraria\ModLoader\Logs\client.log" 

| I'm not really sure if this is a structure helper bug or the other mod's problem when generating. A diagnosis would be greatly appreciated! |

**Comment by ScalarVector1** [comment]
"IceKracken" Is no longer supported and depends on an older version of StructureHelper. You will have to downgrade your version of StructureHelper to use it.

**Comment by InterGypsi** [comment]
thank you very much! Where can I download the previous versions?

**Comment by ScalarVector1** [comment]
https://github.com/ScalarVector1/StructureHelper/releases
